# YAML Lint configuration for GitHub Actions workflows
# Suppress false positives from GitHub Actions schema validation

extends: default

rules:
  # Allow GitHub Actions expressions like ${{ secrets.* }}
  line-length:
    max: 200
    level: warning

  # Don't complain about GitHub Actions syntax
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # GitHub Actions uses specific indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Allow empty values (common in GitHub Actions)
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # Don't enforce key ordering
  key-ordering: disable

  # Allow truthy values (on, off, yes, no)
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
    check-keys: false

# Ignore generated files and third-party workflows
ignore: |
  node_modules/
  .venv/
  dist/
  build/
