name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy_job:
    # Run deploy on push, and on PRs only when PRs are from same-repo (not forks) and not closed
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed' && !github.event.pull_request.head.repo.fork)
    env:
      # Expose token via env to satisfy certain editors that don't understand secrets in expressions
      AZURE_TOKEN: ${{ secrets.AZURE }}
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true

      - name: Build And Deploy
        id: builddeploy
        if: ${{ env.AZURE_TOKEN != '' }}
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9 # v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env: {}

  close_pull_request_job:
    # Close preview environments only for non-fork PRs
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && !github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9 # v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE }}
          action: "close"
          # Include app_location to satisfy some schema validators; action ignores this for 'close'
          app_location: "/"
