name: Python - Edu Blob Organizer CI

on:
  push:
    paths:
      - 'scripts/edu_blob_organizer/**'
      - '.github/workflows/edu-blob-organizer-ci.yml'
  pull_request:
    paths:
      - 'scripts/edu_blob_organizer/**'
      - '.github/workflows/edu-blob-organizer-ci.yml'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/edu_blob_organizer/requirements.txt

      - name: Quick import check
        run: |
          python - <<'PY'
          import importlib
          mods = [
            'azure.identity',
            'azure.storage.blob',
            'azure.storage.filedatalake',
            'azure.core',
            'pdfminer'
          ]
          for m in mods:
            importlib.import_module(m)
          print('imports-ok')
          PY
